
LibItemStatsName = {
	"Attribute",
	"Strength",
	"Agility",
	"Stamina",
	"Intellect",
	"Spirit",
	"Armor",
	-- "Resilience",
	"Defense",
	"Dodge",
	"Parry",
	"Block",
	"Blockvalue",
	"ArmorReduce",
	"Health",
	"HP",
	"MP",
	"ManaRestore",
	"HealthRestore",
	"Resistance",
	"ResistanceNature",
	"ResistanceFire",
	"ResistanceArcane",
	"ResistanceShadow",
	"ResistanceFrost",
	"ResistanceHoly",
	"ResistanceComa",
	"Spell",
	"SpellDamage",
	"Healing",
	"DamageNature",
	"DamageFire",
	"DamageArcane",
	"DamageShadow",
	"DamageFrost",
	"DamageHoly",
	"SpellCrit",
	"SpellHitRating",
	"SpellStrike",
	-- "HasteSpell",
	"ReduceResistance",
	"Attack",
	"AttackDamage",
	"AttackSpeed",
	"AttackPower",
	"AttackCrit",
	"HitRating",
	-- "HasteMelee",
	"RangedAttackDamage",
	"RangedAttackSpeed",
	"RangedAttackPower",
	"RangedAttackCrit",
	"RangedHitRating",
	-- "HasteRanged",
	"RunSpeed",
	"MountSpeed",
	-- "Talent",
	-- "Suit",
	"Daggerskill",
	"Oneaxeskill",
	"Twoaxeskill",
	"Oneswordskill",
	"Twoswordskill",
	"Onemaceskill",
	"Twomaceskill",
	"Bowskill",
	"Gunsskill",
	"Crossbowskill",
}
