-- by yaroot (yaroot#gmail.com)

if(GetLocale() ~= 'zhCN') then return end

local _, addon = ...
local baseLocale = {
    ["Blizzard Frame Options"] = "暴雪框体设置",
    ["Frame Blacklist"] = "框体黑名单",
    ["A binding that belongs to the 'default' binding-set will always be active on your unit frames, unless you override it with another binding."] = "默认组别, 设置将对所有框体有效, 除非有其他组别的相同的按键设置",
    ["A binding that belongs to the 'enemy' binding-set will always be active when clicking on unit frames that display enemy units, i.e. those you can attack. If you click on a unit that you cannot attack, nothing will happen."] = "敌对组别, 设置只对敌对的框体有效, 当你对敌对的框体点击施法时, 这个设置将被触发.",
    ["A binding that belongs to the 'frield' binding-set will only be active when clicking on unit frames that display friendly units, i.e. those you can heal and assist. If you click on a unit that you cannot heal or assist, nothing will happen."] = "友善组别, 该组别设置只对友善的框体有效, 当你对友善的框体点击施法时, 该设置将被触发.",
    ["A binding that belongs to the 'global' binding-set is always active. If the spell requires a target, you will be given the 'casting hand', otherwise the spell will be cast. If the spell is an AOE spell, then you will be given the ground targeting circle."] = "全局组别, 该组别设置始终处于活动状态，如果该法术需要一个目标，将为您提供“施法者”，否则将施放该咒语。如果该法术是AOE法术，那么您将获得地面瞄准圈",
    ["A binding that belongs to the 'hovercast' binding-set is active whenever the mouse is over a unit frame, or a character in the 3D world. This allows you to use 'hovercasting', where you hover over a unit in the world and press a key to cast a spell on them. THese bindings are also active over unit frames."] = "全局组别, 该组别按键设置为悬浮式施法, 将鼠标移动到其他玩家/怪物或者头像框体上将可以直接对其施法.",
    ["A binding that belongs to the 'ooc' binding-set will only be active when the player is out-of-combat, regardless of the other binding-sets this binding belongs to. As soon as the player enters combat, these bindings will no longer be active, so be careful when choosing this binding-set for any spells you use frequently."] = "非战斗组别, 这个组别的设置只在不战斗时有效，无论此组别所属的其他组别如何。.",
    ["A binding that belongs to this binding-set is only active when the player has the given talent specialization active"] = "",
    ["Accept"] = "接受",
    ["Action"] = "动作",
    ["Add new profile"] = "添加新配置",
    ["Attempt to fix the issue introduced in 4.3 with casting on dead targets"] = "尝试解决4.3版本中引入的对死亡目标进行施法时出现的问题",
    ["Bind other"] = "绑定其他",
    ["Bind spell"] = "绑定技能",
    ["Binding"] = "绑定",
    ["Blizzard frame integration options"] = "暴雪框体集中设置",
    ["Cancel"] = "取消",
    ["Change binding"] = "修改绑定",
    ["Change binding: %s"] = "修改绑定: %s",
    ["Clique Binding Configuration"] = "Clique 设置",
    ["Clique binding configuration"] = "Clique 设置",
    ["Clique general options"] = "Clique 常规设置",
    ["Clique: 'default' binding-set"] = "组别: 默认",
    ["Clique: 'enemy' binding-set"] = "组别: 敌对",
    ["Clique: 'friend' binding-set"] = "组别: 友善",
    ["Clique: 'global' binding-set"] = "组别: 全局",
    ["Clique: 'hovercast' binding-set"] = "组别: 悬浮施法",
    ["Clique: 'ooc' binding-set"] = "组别: 非战斗",
    ["Clique: talent set %d binding-set"] = "组别: 天赋 %d 绑定组",
    ["Configure binding: '%s'"] = "设置绑定: '%s'",
    ["Current: "] = "当前: ",
    ["Default"] = "默认",
    ["Delete binding"] = "删除绑定",
    ["Delete profile '%s'"] = "删除配置: '%s'",
    ["Delete profile: %s"] = "删除配置: %s",
    ["Disable out of combat clicks when party members enter combat"] = "当队友进入战斗时禁用 '非战斗' 组别的快捷键",
    ["Edit macro"] = "编辑宏",
    ["Enable/Disable click-sets"] = "设置组别...",
    ["Enemy"] = "敌对",
    ["Frame blacklist"] = "框体黑名单",
    ["Friend"] = "友善",
    ["General Options"] = "常规设置",
    ["Global bindings (no target)"] = "全局按键 (无目标)",
    ["Hovercast bindings (target required)"] = "悬浮按键 (需要目标)",
    ["In order to specify a binding, move your mouse over the button labelled 'Set binding' and either click with your mouse or press a key on your keyboard. You can modify the binding by holding down a combination of the alt, control and shift keys on your keyboard."] = "设置绑定先要将鼠标移动到 '设置绑定' 按钮上, 然后点击需要设置的快捷键. 你可以使用crtl/shift/alt之类的组合键.",
    ["No binding set"] = "无组别",
    ["Open unit menu"] = "打开右键菜单",
    ["Options"] = "设置",
    ["Out-of-combat (ONLY)"] = "仅非战斗",
    ["Profile Management:"] = "配置管理",
    ["Remove spell rank"] = "移除法术等级",
    ["Run custom macro"] = "运行自定义宏",
    ["Save"] = "保存",
    ["Select a binding type"] = "选择绑定类型",
    ["Select an options category"] = "选择设置类别",
    ["Select profile: %s"] = "选择配置: %s",
    ["Set binding"] = "设置绑定",
    ["Set binding: %s"] = "设置绑定: %s",
    ["Swap profiles based on talent spec"] = "随天赋切换配置",
    ["Talent profile: %s"] = "天赋配置: %s",
    ["Talents: %s"] = "天赋: %s",
    ["Target clicked unit"] = "选中点击单位",
    ["Trigger bindings on the 'down' portion of the click (experimental)"] = "Trigger bindings on the 'down' portion of the click (experimental)",
    ["When both the Clique binding configuration window and the spellbook are open, you can set new bindings simply by performing them on the spell icon in your spellbook. Simply move your mouse over a spell and then click or press a key on your keyboard along with any combination of the alt, control, and shift keys. The new binding will be added to your binding configuration."] = "当 Clique 设置界面 和 法术书 同时打开时, 你只要用需要设置的快捷键点击法术就可以将其添加到 Clique 设置中. 将鼠标移动到法术图标上, 同时可以按下 ctrl, alt 和 shift 中的一个或多个, 然后点击鼠标的某一个按键, 这项设置就会被添加.",
    ["You are in Clique binding mode"] = "你现在处于 Clique 设置模式中",
    ["You can use this page to create a custom macro to be run when activating a binding on a unit. When creating this macro you should keep in mind that you will need to specify the target of any actions in the macro by using the 'mouseover' unit, which is the unit you are clicking on. For example, you can do any of the following:\n\n/cast [target=mouseover] Regrowth\n/cast [@mouseover] Regrowth\n/cast [@mouseovertarget] Taunt\n\nHover over the 'Set binding' button below and either click or press a key with any modifiers you would like included. Then edit the box below to contain the macro you would like to have run when this binding is activated."] = "你可以在这页创建一个用于点击施放的自定义宏. 撰写宏时需要注意, 你必须将施法动作的目标指定为 'mouseover'. 例如, 你可以使用以下内容:\n\n/cast [target=mouseover] 愈合\n/cast [@mouseovertarget] 嘲讽\n\n将鼠标移动到 设置绑定 按钮上然后按下鼠标和ctrl/alt/shift键来创建绑定. 然后撰写你需要运行的宏",
}

addon:RegisterLocale('zhCN', baseLocale)
