-- by yaroot (yaroot#gmail.com)

if(GetLocale() ~= 'zhTW') then return end

local _, addon = ...
local baseLocale = {
    ["Blizzard Frame Options"] = "暴雪框體設置",
    ["Frame Blacklist"] = "框體黑名單",
    ["A binding that belongs to the 'default' binding-set will always be active on your unit frames, unless you override it with another binding."] = "默認組別, 設置將對所有框體有效, 除非有其他組別的相同的按鍵設置",
    ["A binding that belongs to the 'enemy' binding-set will always be active when clicking on unit frames that display enemy units, i.e. those you can attack. If you click on a unit that you cannot attack, nothing will happen."] = "敵對組別, 設置只對敵對的框體有效, 當你對敵對的框體點擊施法時, 這個設置將被觸發.",
    ["A binding that belongs to the 'frield' binding-set will only be active when clicking on unit frames that display friendly units, i.e. those you can heal and assist. If you click on a unit that you cannot heal or assist, nothing will happen."] = "友善組別, 該組別設置只對友善的框體有效, 當你對友善的框體點擊施法時, 該設置將被觸發.",
    ["A binding that belongs to the 'global' binding-set is always active. If the spell requires a target, you will be given the 'casting hand', otherwise the spell will be cast. If the spell is an AOE spell, then you will be given the ground targeting circle."] = "通用群組別, 該組別設置始終處於活動狀態，如果該法術需要一個目標，將為您提供“施法者”，否則將施放該咒語。如果該法術是AOE法術，那麼您將獲得地面瞄準圈",
    ["A binding that belongs to the 'hovercast' binding-set is active whenever the mouse is over a unit frame, or a character in the 3D world. This allows you to use 'hovercasting', where you hover over a unit in the world and press a key to cast a spell on them. THese bindings are also active over unit frames."] = "通用群組別, 該組別按鍵設置為懸浮式施法, 將滑鼠移動到其他玩家/怪物或者頭像框體上將可以直接對其施法.",
    ["A binding that belongs to the 'ooc' binding-set will only be active when the player is out-of-combat, regardless of the other binding-sets this binding belongs to. As soon as the player enters combat, these bindings will no longer be active, so be careful when choosing this binding-set for any spells you use frequently."] = "非戰鬥組別, 這個組別的設置只在不戰鬥時有效，無論此組別所屬的其他組別如何。.",
    ["A binding that belongs to this binding-set is only active when the player has the given talent specialization active"] = "",
    ["Accept"] = "接受",
    ["Action"] = "動作",
    ["Add new profile"] = "添加新配置",
    ["Attempt to fix the issue introduced in 4.3 with casting on dead targets"] = "嘗試解決4.3版本中引入的對死亡目標進行施法時出現的問題",
    ["Bind other"] = "綁定其他",
    ["Bind spell"] = "綁定技能",
    ["Binding"] = "綁定",
    ["Blizzard frame integration options"] = "暴雪框體集中設置",
    ["Cancel"] = "取消",
    ["Change binding"] = "修改綁定",
    ["Change binding: %s"] = "修改綁定: %s",
    ["Clique Binding Configuration"] = "Clique 設置",
    ["Clique binding configuration"] = "Clique 設置",
    ["Clique general options"] = "Clique 常規設置",
    ["Clique: 'default' binding-set"] = "組別: 默認",
    ["Clique: 'enemy' binding-set"] = "組別: 敵對",
    ["Clique: 'friend' binding-set"] = "組別: 友善",
    ["Clique: 'global' binding-set"] = "組別: 全域",
    ["Clique: 'hovercast' binding-set"] = "組別: 懸浮施法",
    ["Clique: 'ooc' binding-set"] = "組別: 非戰鬥",
    ["Clique: talent set %d binding-set"] = "組別: 天賦 %d 綁定組",
    ["Configure binding: '%s'"] = "設置綁定: '%s'",
    ["Current: "] = "當前: ",
    ["Default"] = "默認",
    ["Delete binding"] = "刪除綁定",
    ["Delete profile '%s'"] = "刪除配置: '%s'",
    ["Delete profile: %s"] = "刪除配置: %s",
    ["Disable out of combat clicks when party members enter combat"] = "當隊友進入戰鬥時禁用 '非戰鬥' 組別的快速鍵",
    ["Edit macro"] = "編輯宏",
    ["Enable/Disable click-sets"] = "設置組別...",
    ["Enemy"] = "敵對",
    ["Frame blacklist"] = "框體黑名單",
    ["Friend"] = "友善",
    ["General Options"] = "常規設置",
    ["Global bindings (no target)"] = "全域按鍵 (無目標)",
    ["Hovercast bindings (target required)"] = "懸浮按鍵 (需要目標)",
    ["In order to specify a binding, move your mouse over the button labelled 'Set binding' and either click with your mouse or press a key on your keyboard. You can modify the binding by holding down a combination of the alt, control and shift keys on your keyboard."] = "設置綁定先要將滑鼠移動到 '設置綁定' 按鈕上, 然後點擊需要設置的快速鍵. 你可以使用crtl/shift/alt之類的複合鍵.",
    ["No binding set"] = "無組別",
    ["Open unit menu"] = "打開右鍵菜單",
    ["Options"] = "設置",
    ["Out-of-combat (ONLY)"] = "僅非戰鬥",
    ["Profile Management:"] = "配置管理",
    ["Remove spell rank"] = "移除法術等級",
    ["Run custom macro"] = "運行自訂宏",
    ["Save"] = "保存",
    ["Select a binding type"] = "選擇綁定類型",
    ["Select an options category"] = "選擇設置類別",
    ["Select profile: %s"] = "選擇配置: %s",
    ["Set binding"] = "設置綁定",
    ["Set binding: %s"] = "設置綁定: %s",
    ["Swap profiles based on talent spec"] = "隨天賦切換配置",
    ["Talent profile: %s"] = "天賦配置: %s",
    ["Talents: %s"] = "天賦: %s",
    ["Target clicked unit"] = "選中點擊單位",
    ["Trigger bindings on the 'down' portion of the click (experimental)"] = "Trigger bindings on the 'down' portion of the click (experimental)",
    ["When both the Clique binding configuration window and the spellbook are open, you can set new bindings simply by performing them on the spell icon in your spellbook. Simply move your mouse over a spell and then click or press a key on your keyboard along with any combination of the alt, control, and shift keys. The new binding will be added to your binding configuration."] = "當 Clique 設置介面 和 法術書 同時打開時, 你只要用需要設置的快速鍵點擊法術就可以將其添加到 Clique 設置中. 將滑鼠移動到法術圖示上, 同時可以按下 ctrl, alt 和 shift 中的一個或多個, 然後點擊滑鼠的某一個按鍵, 這項設置就會被添加.",
    ["You are in Clique binding mode"] = "你現在處於 Clique 設置模式中",
    ["You can use this page to create a custom macro to be run when activating a binding on a unit. When creating this macro you should keep in mind that you will need to specify the target of any actions in the macro by using the 'mouseover' unit, which is the unit you are clicking on. For example, you can do any of the following:\n\n/cast [target=mouseover] Regrowth\n/cast [@mouseover] Regrowth\n/cast [@mouseovertarget] Taunt\n\nHover over the 'Set binding' button below and either click or press a key with any modifiers you would like included. Then edit the box below to contain the macro you would like to have run when this binding is activated."] = "你可以在這頁創建一個用於點擊施放的自訂宏. 撰寫巨集時需要注意, 你必須將施法動作的目標指定為 'mouseover'. 例如, 你可以使用以下內容:\n\n/cast [target=mouseover] 癒合\n/cast [@mouseovertarget] 嘲諷\n\n將滑鼠移動到 設置綁定 按鈕上然後按下滑鼠和ctrl/alt/shift鍵來創建綁定. 然後撰寫你需要運行的巨集",
}

addon:RegisterLocale('zhTW', baseLocale)
